Repository frenck/python-adguardhome, pull requests merged in 2023-01, with the labels that each got.

#678 :arrow_up: Update all (sub)dependencies
  poetry.lock
Labels: dependencies

#679 Use dataclasses to clean up a little
  src/adguardhome/filtering.py
  src/adguardhome/parental.py
  src/adguardhome/querylog.py
  src/adguardhome/safebrowsing.py
  src/adguardhome/safesearch.py
  src/adguardhome/stats.py
Labels: refactor

#677 Skip Content-Type header
  src/adguardhome/adguardhome.py
Labels: bugfix

#683 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
Labels: maintenance

#682 :snake: Add Python 3.11 support
  .github/workflows/tests.yaml
  .github/workflows/typing.yaml
  pyproject.toml
Labels: new-feature

#684 Fix content-type handing for JSON requests
  src/adguardhome/adguardhome.py
Labels: bugfix
